//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace consumeWS.NoreenWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://noreenFirstWebService.org/", ConfigurationName="NoreenWS.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://noreenFirstWebService.org/add", ReplyAction="*")]
        int add(int nbr1, int nbr2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://noreenFirstWebService.org/add", ReplyAction="*")]
        System.Threading.Tasks.Task<int> addAsync(int nbr1, int nbr2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://noreenFirstWebService.org/mul", ReplyAction="*")]
        int mul(int nbr1, int nbr2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://noreenFirstWebService.org/mul", ReplyAction="*")]
        System.Threading.Tasks.Task<int> mulAsync(int nbr1, int nbr2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : global::consumeWS.NoreenWS.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<global::consumeWS.NoreenWS.WebService1Soap>, global::consumeWS.NoreenWS.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int add(int nbr1, int nbr2) {
            return base.Channel.add(nbr1, nbr2);
        }
        
        public System.Threading.Tasks.Task<int> addAsync(int nbr1, int nbr2) {
            return base.Channel.addAsync(nbr1, nbr2);
        }
        
        public int mul(int nbr1, int nbr2) {
            return base.Channel.mul(nbr1, nbr2);
        }
        
        public System.Threading.Tasks.Task<int> mulAsync(int nbr1, int nbr2) {
            return base.Channel.mulAsync(nbr1, nbr2);
        }
    }
}
